#constants.py
 
# Screen Dimensions
SCREEN_WIDTH = 80 
SCREEN_HEIGHT = 45 

# Actual map size 
MAP_WIDTH = 200 
MAP_HEIGHT = 100 

# Map viewport 
MAP_VIEWPORT_WIDTH = 60
MAP_VIEWPORT_HEIGHT = 40

# UI Panel dimensions
STATS_PANEL_X = 60
STATS_PANEL_Y = 0
STATS_PANEL_WIDTH = 20
STATS_PANEL_HEIGHT = 19

INVENTORY_PANEL_X = 60
INVENTORY_PANEL_Y = 20
INVENTORY_PANEL_WIDTH = 20
INVENTORY_PANEL_HEIGHT = 19

LOG_PANEL_X = 0
LOG_PANEL_Y = 39
LOG_PANEL_WIDTH = 80
LOG_PANEL_HEIGHT = 5

# Dungeon generation
ROOM_MAX_SIZE = 20
ROOM_MIN_SIZE = 10
MAX_ROOMS = 200

MAX_MONSTERS_PER_ROOM = 6
MAX_ITEMS_PER_ROOM = 4