#constants.py
 
# Screen Dimensions
SCREEN_WIDTH = 80 
SCREEN_HEIGHT = 45 

# Actual map size (can be much larger when you add camera)
MAP_WIDTH = 200 # Will increase to 200+ later
MAP_HEIGHT = 100  # Will increase to 100+ later

# Map viewport (visible portion on screen)
MAP_VIEWPORT_WIDTH = SCREEN_WIDTH
MAP_VIEWPORT_HEIGHT = SCREEN_HEIGHT

# UI Panel dimensions
STATS_PANEL_X = 60
STATS_PANEL_Y = 0
STATS_PANEL_WIDTH = 19
STATS_PANEL_HEIGHT = 21

INVENTORY_PANEL_X = 60
INVENTORY_PANEL_Y = 22
INVENTORY_PANEL_WIDTH = 19
INVENTORY_PANEL_HEIGHT = 21

LOG_PANEL_X = 0
LOG_PANEL_Y = 39
LOG_PANEL_WIDTH = 80
LOG_PANEL_HEIGHT = 6

# Dungeon generation
ROOM_MAX_SIZE = 10
ROOM_MIN_SIZE = 5
MAX_ROOMS = 200

MAX_MONSTERS_PER_ROOM = 6
MAX_ITEMS_PER_ROOM = 4